version: '3.8'

services:
  users:
    build:
      context: ./users
    container_name: users
    ports:
      - "7007:8000"
    networks:
      - network
    depends_on:
      - db
    env_file: .env
#    command: >
#      sh -c "alembic upgrade head && exec uvicorn main:app --host 0.0.0.0 --port 8000"


  posts:
    build:
      context: ./posts
    container_name: posts
    ports:
      - "7001:8000"
    env_file: .env
    depends_on:
      - users
    networks:
      - network

  feeds:
    build:
      context: ./feeds
    container_name: feeds
    ports:
      - "7002:8000"
    env_file: .env
    depends_on:
      - users
      - posts
    networks:
      - network

  db:
    container_name: db
    image: 'postgres:14'
    restart: always
    env_file:
      - .env
    ports:
      - '${POSTGRES_PORT}:5432'
    networks:
      - network

networks:
  network:
    driver: bridge