version: '3.8'

services:
  users:
    build:
      context: ./users
    container_name: users
    ports:
      - "5000:8000"
    networks:
      - network

  posts:
    build:
      context: ./posts
    container_name: posts
    ports:
      - "5001:8000"
    env_file: .env
    depends_on:
      - users
    networks:
      - network

  feeds:
    build:
      context: ./feeds
    container_name: feeds
    ports:
      - "5002:8000"
    env_file: .env
    depends_on:
      - users
      - posts
    networks:
      - network

networks:
  network:
    driver: bridge